In [1]:
#import dependancies
import pandas as pd
import numpy as np
import requests 
import time 
import json

from census_key import api_key

In [2]:
markets_df = pd.read_csv('Markets_for_api.csv', encoding = "ISO-8859-1", dtype=str)

In [3]:
markets_df.head(20)

,Market_id,Market_name,Market_state,State_code,FIPS_code,Lat,Long
0,1,Albany,NY,36,36001,42.6526,\t-73.7562
1,2,Atlanta,GA,13,13121,\t33.753746,\t-84.386330
2,3,Baltimore,MD,24,24510,\t39.299236,\t-76.609383
3,4,Boise,ID,16,16001,\t43.618881,\t-116.215019
4,5,Boston,MA,25,25025,\t42.361145,\t-71.057083
5,6,Buffalo,NY,36,36029,\t42.880230,\t-78.878738
6,7,Charlotte,NC,37,37119,\t35.227085,\t-80.843124
7,8,Chicago,IL,17,17031,\t41.881832,\t-87.623177
8,9,Cincinnati,OH,39,39061,\t39.103119,\t-84.512016
9,10,Columbus,OH,39,39049,\t39.983334,\t-82.983330
10,11,Dallas,TX,48,48113,\t32.779167,\t-96.808891
11,12,Denver,CO,08,08031,\t39.742043,\t-104.991531
12,13,Detroit,MI,26,26163,\t42.331429,\t-83.045753
13,14,Grand Rapids,MI,26,26081,\t42.963795,\t-85.670006
14,15,Harrisburg,PA,42,42043,\t40.263680,\t-76.890739
15,16,Hartford,CT,09,09003,\t41.763710,\t-72.685097
16,17,Houston,TX,48,48201,\t29.749907,\t-95.358421
17,18,Indianapolis,IN,18,18053,\t39.791000,\t-86.148003
18,19,Jacksonville,FL,12,12031,\t30.332184,\t-81.655647
19,20,Las Vegas,NV,32,32003,\t36.114647,\t-115.172813

In [4]:
markets_df["County_code"]=""

for index, row in markets_df.iterrows():
    FIPS = markets_df.loc[index,"FIPS_code"]
    county_code = FIPS[2:5]
    markets_df.loc[index,"County_code"] = county_code
    
#markets_df.head()

In [5]:
##Create holders for Total Population, White Alone Population, Age 20-24, Age 25 - 29, Age 30 - 34, Age 35 - 39 and Median Income
markets_df["Total_population"]=""
markets_df["Non_White_pop"]=""
markets_df["Diversity%"]=""
markets_df["Millenial_pop"]=""
markets_df["Millenial%"]=""
markets_df["Median_income"]=""

#markets_df.tail()
#There are 42 markets, just FYI

In [6]:
print("Log Start")
print("--------------------------")

for index, row in markets_df.iterrows():
    
    #set needed variables
    county = markets_df.loc[index, "County_code"]
    state = markets_df.loc[index, "State_code"]
    data = "B01001_001E,B01001A_001E,B01001_032E,B01001_033E,B01001_034E,B01001_035E,B01001_036E,B01001_037E,B01001_008E,B01001_009E,B01001_010E,B01001_011E,B01001_012E,B01001_013E,B06011_001E"
        
    query_url = "http://api.census.gov/data/2017/acs/acs1?get=" + str(data) + "&for=county:" + str(county) + "&in=state:" + str(state) + "&key=" + str(api_key)
    
    try:
        response = requests.get(query_url).json()
    
        census_data = response[1]

        for i in range(0, len(census_data)): 
            census_data[i] = int(census_data[i]) 

        print(markets_df.loc[index,"Market_id"])
        
        try:
            #sum all age data
            all_females = sum(census_data[2:8])
            all_males = sum(census_data[8:14])
            millenials = all_females + all_males
            
            total_pop = census_data[0]
            white_pop = census_data[1]
            
            non_white = total_pop - white_pop
            #print(total_pop, non_white)
            
            diversity = non_white/total_pop
            #print(diversity)

        except:
            print('error with conversion')
        
        try:
            markets_df.loc[index, "Total_population"] = total_pop
            markets_df.loc[index, "Non_White_pop"]= non_white
            markets_df.loc[index,"Diversity%"]= diversity
            markets_df.loc[index,"Millenial_pop"]= millenials
            markets_df.loc[index,"Millenial%"]= millenials/total_pop
            markets_df.loc[index,"Median_income"]=census_data[14]
        
        except:
            print('error with api call')
            
    except:
        print(query_url)


print("---------------")
print("Log End")

Log Start
--------------------------
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
http://api.census.gov/data/2017/acs/acs1?get=B01001_001E,B01001A_001E,B01001_032E,B01001_033E,B01001_034E,B01001_035E,B01001_036E,B01001_037E,B01001_008E,B01001_009E,B01001_010E,B01001_011E,B01001_012E,B01001_013E,B06011_001E&for=county:&in=state:0&key=5b32564c5f4ebf42969c99f2ac96affff18bb411
---------------
Log End

In [7]:
#Market_id 43 (last one) fails because it's the total u.s., so there's no FIPS county or state to call. 
#Build a custom call to grab total us data. Region seems to be as aggregate as we can get, so we'll need to sum

query_url = "http://api.census.gov/data/2017/acs/acs1?get=" + str(data) + "&for=region:*&key=" + str(api_key)


response = requests.get(query_url).json()
        
northeast = response[1]
midwest = response[2]
south = response[3]
west = response[4]

try:
    for i in range(0,(len(northeast)-1)):
        northeast[i] = int(northeast[i])
                       
    for i in range(0,(len(midwest)-1)):
        midwest[i] = int(midwest[i])
                       
    for i in range(0,(len(south)-1)):
        south[i] = int(south[i])
                       
    for i in range(0,(len(west)-1)):
        west[i] = int(west[i])
        
except:
    print("couldn't convert")


total_pop = northeast[0] + midwest[0] + south[0]+ west[0]
print(total_pop)

all_females = sum(northeast[2:8])+ sum(midwest[2:8]) + sum(south[2:8]) + sum(west[2:8])
all_males = sum(northeast[8:14])+sum(midwest[8:14])+sum(south[8:14])+sum(west[8:14])
millenials = all_females + all_males
print(millenials)

white_pop = northeast[1] + midwest[1] + south[1]+ west[1]
non_white = total_pop - white_pop
diversity = non_white/total_pop

#taking the average of the median
median_inc = (northeast[14] + midwest[14] + south[14] + west[14])/4

markets_df.loc[42, "Total_population"] = total_pop
markets_df.loc[42, "Non_White_pop"]= non_white
markets_df.loc[42,"Diversity%"]= diversity
markets_df.loc[42,"Millenial_pop"]= millenials
markets_df.loc[42,"Millenial%"]= millenials/total_pop
markets_df.loc[42,"Median_income"]= median_inc

325719178
88289034

In [8]:
markets_df

,Market_id,Market_name,Market_state,State_code,FIPS_code,Lat,Long,County_code,Total_population,Non_White_pop,Diversity%,Millenial_pop,Millenial%,Median_income
0,1,Albany,NY,36,36001,42.6526,\t-73.7562,001,309612,77716,0.251011,91140,0.294368,34052
1,2,Atlanta,GA,13,13121,\t33.753746,\t-84.386330,121,1041423,576002,0.553091,334400,0.321099,35434
2,3,Baltimore,MD,24,24510,\t39.299236,\t-76.609383,510,611648,427660,0.699193,205749,0.336385,28426
3,4,Boise,ID,16,16001,\t43.618881,\t-116.215019,001,456849,45269,0.0990896,126439,0.276763,31462
4,5,Boston,MA,25,25025,\t42.361145,\t-71.057083,025,797939,352816,0.442159,319786,0.400765,32277
5,6,Buffalo,NY,36,36029,\t42.880230,\t-78.878738,029,925528,208810,0.225612,243552,0.263149,30399
6,7,Charlotte,NC,37,37119,\t35.227085,\t-80.843124,119,1076837,499264,0.463639,337665,0.313571,34131
7,8,Chicago,IL,17,17031,\t41.881832,\t-87.623177,031,5211263,2272531,0.436081,1567543,0.300799,31860
8,9,Cincinnati,OH,39,39061,\t39.103119,\t-84.512016,061,813822,262478,0.322525,227950,0.280098,30836
9,10,Columbus,OH,39,39049,\t39.983334,\t-82.983330,049,1291981,434926,0.336635,421416,0.326178,31402
10,11,Dallas,TX,48,48113,\t32.779167,\t-96.808891,113,2618148,999856,0.381894,793302,0.303001,30499
11,12,Denver,CO,08,08031,\t39.742043,\t-104.991531,031,704621,173278,0.245917,264819,0.375832,38507
12,13,Detroit,MI,26,26163,\t42.331429,\t-83.045753,163,1753616,822959,0.469293,463340,0.26422,26163
13,14,Grand Rapids,MI,26,26081,\t42.963795,\t-85.670006,081,648594,130562,0.2013,188337,0.290377,30031
14,15,Harrisburg,PA,42,42043,\t40.263680,\t-76.890739,043,275710,81369,0.295125,71789,0.260379,31679
15,16,Hartford,CT,09,09003,\t41.763710,\t-72.685097,003,895388,262013,0.292625,232742,0.259934,35873
16,17,Houston,TX,48,48201,\t29.749907,\t-95.358421,201,4652980,1683532,0.361818,1409907,0.303012,30636
17,18,Indianapolis,IN,18,18053,\t39.791000,\t-86.148003,053,66491,8414,0.126543,16104,0.242198,22166
18,19,Jacksonville,FL,12,12031,\t30.332184,\t-81.655647,031,937934,378454,0.403497,280899,0.299487,28906
19,20,Las Vegas,NV,32,32003,\t36.114647,\t-115.172813,003,2204079,907485,0.41173,622174,0.282283,30131
20,21,Los Angeles,CA,06,06037,\t34.052235,\t-118.243683,037,10163507,5115638,0.503334,3081754,0.303218,28608
21,22,Louisville,KY,21,21111,\t38.328732,\t-85.764771,111,771158,220233,0.285587,213485,0.276837,30797
22,23,Miami,FL,12,12086,\t25.761681,\t-80.191788,086,2751796,675090,0.245327,752289,0.273381,23248
23,24,Nashville,TN,47,47037,\t36.174465,\t-86.767960,037,691243,243574,0.352371,240545,0.347989,31576
24,25,New Orleans,LA,22,22071,\t29.951065,\t-90.071533,071,393292,260168,0.661514,125873,0.32005,23819
25,26,New York City,NY,36,36085,\t40.730610,\t-73.935242,085,479458,127826,0.266605,122877,0.256283,37299
26,27,Orlando,FL,12,12095,\t28.538336,\t-81.379234,095,1348975,517507,0.38363,434304,0.321951,26472
27,28,Philadelphia,PA,42,42101,\t39.952583,\t-75.165222,101,1580863,915803,0.579306,521947,0.330166,25640
28,29,Phoenix,AZ,04,04013,\t33.448376,\t-112.074036,013,4307033,964741,0.223992,1196209,0.277734,31540
29,30,Pittsburgh,PA,42,42003,\t40.440624,\t-79.995888,003,1223048,248527,0.203203,334728,0.273683,31977
30,31,Portland,OR,41,41051,\t45.523064,\t-122.676483,051,807555,180650,0.2237,269902,0.334221,32033
31,32,Raleigh,NC,37,37183,\t35.787743,\t-78.644257,183,1072203,371983,0.346933,309196,0.288374,38598
32,33,Richmond,VA,51,51760,\t37.541290,\t-77.434769,760,227032,123416,0.543606,82997,0.365574,24447
33,34,Roanoke,VA,51,51770,\t37.270969,\t-79.941429,770,99837,38650,0.387131,26888,0.269319,24042
34,35,Sacramento,CA,06,06067,\t38.590576,\t-121.489906,067,1530615,671763,0.438884,442575,0.289148,31267
35,36,San Diego,CA,06,06073,\t32.715736,\t-117.161087,073,3337685,1012551,0.303369,1031679,0.3091,32687
36,37,San Francisco,CA,06,06075,\t37.773972,\t-122.431297,075,884363,481396,0.544342,334539,0.378282,50398
37,38,Seattle,WA,53,53033,\t47.608013,\t-122.335167,033,2188649,790673,0.361261,701290,0.320421,42989
38,39,Spokane,WA,53,53063,\t47.658779,\t-117.426048,063,506152,60855,0.120231,141748,0.28005,29353
39,40,St. Louis,MO,29,29510,\t38.627003,\t-90.199402,510,308626,165670,0.536799,106016,0.34351,26370
40,41,Syracuse,NY,36,36067,\t43.088947,\t-76.154480,067,465398,95663,0.205551,122344,0.26288,31534
41,42,Tampa,FL,12,12057,\t27.964157,\t-82.452606,057,1408566,390732,0.277397,403727,0.286623,28415
42,43,TotalUS,US,0,0,0,0,,325719178,90211721,0.276962,88289034,0.271059,30428

In [9]:
markets_df.to_csv("Markets_demo_2017.csv")