In [1]:
#import dependancies
import pandas as pd
import numpy as np
import requests 
import time 
import json

from census_key import api_key

In [2]:
markets_df = pd.read_csv('Markets_for_api.csv', encoding = "ISO-8859-1", dtype=str)

In [3]:
markets_df.head(20)

,Market_id,Market_name,Market_state,State_code,FIPS_code,Lat,Long
0,1,Albany,NY,36,36001,42.6526,\t-73.7562
1,2,Atlanta,GA,13,13121,\t33.753746,\t-84.386330
2,3,Baltimore,MD,24,24510,\t39.299236,\t-76.609383
3,4,Boise,ID,16,16001,\t43.618881,\t-116.215019
4,5,Boston,MA,25,25025,\t42.361145,\t-71.057083
5,6,Buffalo,NY,36,36029,\t42.880230,\t-78.878738
6,7,Charlotte,NC,37,37119,\t35.227085,\t-80.843124
7,8,Chicago,IL,17,17031,\t41.881832,\t-87.623177
8,9,Cincinnati,OH,39,39061,\t39.103119,\t-84.512016
9,10,Columbus,OH,39,39049,\t39.983334,\t-82.983330
10,11,Dallas,TX,48,48113,\t32.779167,\t-96.808891
11,12,Denver,CO,08,08031,\t39.742043,\t-104.991531
12,13,Detroit,MI,26,26163,\t42.331429,\t-83.045753
13,14,Grand Rapids,MI,26,26081,\t42.963795,\t-85.670006
14,15,Harrisburg,PA,42,42043,\t40.263680,\t-76.890739
15,16,Hartford,CT,09,09003,\t41.763710,\t-72.685097
16,17,Houston,TX,48,48201,\t29.749907,\t-95.358421
17,18,Indianapolis,IN,18,18053,\t39.791000,\t-86.148003
18,19,Jacksonville,FL,12,12031,\t30.332184,\t-81.655647
19,20,Las Vegas,NV,32,32003,\t36.114647,\t-115.172813

In [4]:
markets_df["County_code"]=""

for index, row in markets_df.iterrows():
    FIPS = markets_df.loc[index,"FIPS_code"]
    county_code = FIPS[2:5]
    markets_df.loc[index,"County_code"] = county_code
    
#markets_df.head()

In [5]:
##Create holders for Total Population, White Alone Population, Age 20-24, Age 25 - 29, Age 30 - 34, Age 35 - 39 and Median Income
markets_df["Total_population"]=""
markets_df["Non_White_pop"]=""
markets_df["Diversity%"]=""
markets_df["Millenial_pop"]=""
markets_df["Millenial%"]=""
markets_df["Median_income"]=""

#markets_df.tail()
#There are 42 markets, just FYI

In [6]:
print("Log Start")
print("--------------------------")

for index, row in markets_df.iterrows():
    
    #set needed variables
    county = markets_df.loc[index, "County_code"]
    state = markets_df.loc[index, "State_code"]
    data = "B01001_001E,B01001A_001E,B01001_032E,B01001_033E,B01001_034E,B01001_035E,B01001_036E,B01001_037E,B01001_008E,B01001_009E,B01001_010E,B01001_011E,B01001_012E,B01001_013E,B06011_001E"
        
    query_url = "http://api.census.gov/data/2016/acs/acs1?get=" + str(data) + "&for=county:" + str(county) + "&in=state:" + str(state) + "&key=" + str(api_key)
    
    try:
        response = requests.get(query_url).json()
    
        census_data = response[1]

        for i in range(0, len(census_data)): 
            census_data[i] = int(census_data[i]) 

        print(markets_df.loc[index,"Market_id"])
        
        try:
            #sum all age data
            all_females = sum(census_data[2:8])
            all_males = sum(census_data[8:14])
            millenials = all_females + all_males
            
            total_pop = census_data[0]
            white_pop = census_data[1]
            
            non_white = total_pop - white_pop
            #print(total_pop, non_white)
            
            diversity = non_white/total_pop
            #print(diversity)

        except:
            print('error with conversion')
        
        try:
            markets_df.loc[index, "Total_population"] = total_pop
            markets_df.loc[index, "Non_White_pop"]= non_white
            markets_df.loc[index,"Diversity%"]= diversity
            markets_df.loc[index,"Millenial_pop"]= millenials
            markets_df.loc[index,"Millenial%"]= millenials/total_pop
            markets_df.loc[index,"Median_income"]=census_data[14]
        
        except:
            print('error with api call')
            
    except:
        print(query_url)


print("---------------")
print("Log End")

Log Start
--------------------------
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
http://api.census.gov/data/2016/acs/acs1?get=B01001_001E,B01001A_001E,B01001_032E,B01001_033E,B01001_034E,B01001_035E,B01001_036E,B01001_037E,B01001_008E,B01001_009E,B01001_010E,B01001_011E,B01001_012E,B01001_013E,B06011_001E&for=county:&in=state:0&key=5b32564c5f4ebf42969c99f2ac96affff18bb411
---------------
Log End

In [7]:
#Market_id 43 (last one) fails because it's the total u.s., so there's no FIPS county or state to call. 
#Build a custom call to grab total us data. Region seems to be as aggregate as we can get, so we'll need to sum

query_url = "http://api.census.gov/data/2016/acs/acs1?get=" + str(data) + "&for=region:*&key=" + str(api_key)


response = requests.get(query_url).json()
        
northeast = response[1]
midwest = response[2]
south = response[3]
west = response[4]

try:
    for i in range(0,(len(northeast)-1)):
        northeast[i] = int(northeast[i])
                       
    for i in range(0,(len(midwest)-1)):
        midwest[i] = int(midwest[i])
                       
    for i in range(0,(len(south)-1)):
        south[i] = int(south[i])
                       
    for i in range(0,(len(west)-1)):
        west[i] = int(west[i])
        
except:
    print("couldn't convert")


total_pop = northeast[0] + midwest[0] + south[0]+ west[0]
print(total_pop)

all_females = sum(northeast[2:8])+ sum(midwest[2:8]) + sum(south[2:8]) + sum(west[2:8])
all_males = sum(northeast[8:14])+sum(midwest[8:14])+sum(south[8:14])+sum(west[8:14])
millenials = all_females + all_males
print(millenials)

white_pop = northeast[1] + midwest[1] + south[1]+ west[1]
non_white = total_pop - white_pop
diversity = non_white/total_pop

#taking the average of the median
median_inc = (northeast[14] + midwest[14] + south[14] + west[14])/4

markets_df.loc[42, "Total_population"] = total_pop
markets_df.loc[42, "Non_White_pop"]= non_white
markets_df.loc[42,"Diversity%"]= diversity
markets_df.loc[42,"Millenial_pop"]= millenials
markets_df.loc[42,"Millenial%"]= millenials/total_pop
markets_df.loc[42,"Median_income"]= median_inc

323127515
87413147

In [8]:
markets_df

,Market_id,Market_name,Market_state,State_code,FIPS_code,Lat,Long,County_code,Total_population,Non_White_pop,Diversity%,Millenial_pop,Millenial%,Median_income
0,1,Albany,NY,36,36001,42.6526,\t-73.7562,001,308846,78015,0.252602,91345,0.295762,31505
1,2,Atlanta,GA,13,13121,\t33.753746,\t-84.386330,121,1023336,567804,0.554856,319104,0.311827,34145
2,3,Baltimore,MD,24,24510,\t39.299236,\t-76.609383,510,614664,425404,0.692092,205273,0.33396,27617
3,4,Boise,ID,16,16001,\t43.618881,\t-116.215019,001,444028,41177,0.0927351,123537,0.278219,30690
4,5,Boston,MA,25,25025,\t42.361145,\t-71.057083,025,784230,352165,0.449058,309286,0.394382,31657
5,6,Buffalo,NY,36,36029,\t42.880230,\t-78.878738,029,921046,202076,0.219398,247575,0.268798,30187
6,7,Charlotte,NC,37,37119,\t35.227085,\t-80.843124,119,1054835,479904,0.454956,324562,0.30769,32763
7,8,Chicago,IL,17,17031,\t41.881832,\t-87.623177,031,5203499,2284040,0.438943,1565547,0.300864,30986
8,9,Cincinnati,OH,39,39061,\t39.103119,\t-84.512016,061,809099,266221,0.329034,220920,0.273044,30319
9,10,Columbus,OH,39,39049,\t39.983334,\t-82.983330,049,1264518,409284,0.323668,412408,0.326138,30768
10,11,Dallas,TX,48,48113,\t32.779167,\t-96.808891,113,2574984,983797,0.382059,785509,0.305054,28917
11,12,Denver,CO,08,08031,\t39.742043,\t-104.991531,031,693060,170776,0.246409,258905,0.373568,35650
12,13,Detroit,MI,26,26163,\t42.331429,\t-83.045753,163,1749366,825235,0.471734,457883,0.261742,24505
13,14,Grand Rapids,MI,26,26081,\t42.963795,\t-85.670006,081,642173,127458,0.198479,186619,0.290605,28325
14,15,Harrisburg,PA,42,42043,\t40.263680,\t-76.890739,043,273707,79916,0.291976,70630,0.25805,32070
15,16,Hartford,CT,09,09003,\t41.763710,\t-72.685097,003,892389,255964,0.28683,224128,0.251155,35971
16,17,Houston,TX,48,48201,\t29.749907,\t-95.358421,201,4589928,1708934,0.372323,1400002,0.305016,29287
17,18,Indianapolis,IN,18,18053,\t39.791000,\t-86.148003,053,66937,7958,0.118888,16936,0.253014,21065
18,19,Jacksonville,FL,12,12031,\t30.332184,\t-81.655647,031,926255,366175,0.395329,276851,0.298893,28668
19,20,Las Vegas,NV,32,32003,\t36.114647,\t-115.172813,003,2155664,825610,0.382996,607921,0.282011,28049
20,21,Los Angeles,CA,06,06037,\t34.052235,\t-118.243683,037,10137915,5044017,0.49754,3062044,0.302039,26661
21,22,Louisville,KY,21,21111,\t38.328732,\t-85.764771,111,765352,214277,0.279972,207207,0.270734,29663
22,23,Miami,FL,12,12086,\t25.761681,\t-80.191788,086,2712945,693030,0.255453,747473,0.275521,22248
23,24,Nashville,TN,47,47037,\t36.174465,\t-86.767960,037,684410,242209,0.353895,237510,0.347029,30604
24,25,New Orleans,LA,22,22071,\t29.951065,\t-90.071533,071,391495,258061,0.659168,129759,0.331445,25202
25,26,New York City,NY,36,36085,\t40.730610,\t-73.935242,085,476015,123485,0.259414,124850,0.262282,37165
26,27,Orlando,FL,12,12095,\t28.538336,\t-81.379234,095,1314367,462654,0.351998,424648,0.323082,26679
27,28,Philadelphia,PA,42,42101,\t39.952583,\t-75.165222,101,1567872,933761,0.595559,519508,0.331346,24237
28,29,Phoenix,AZ,04,04013,\t33.448376,\t-112.074036,013,4242997,1015487,0.239332,1177134,0.27743,30278
29,30,Pittsburgh,PA,42,42003,\t40.440624,\t-79.995888,003,1225365,242386,0.197807,338263,0.276051,30743
30,31,Portland,OR,41,41051,\t45.523064,\t-122.676483,051,799766,169458,0.211884,271056,0.338919,31630
31,32,Raleigh,NC,37,37183,\t35.787743,\t-78.644257,183,1046791,358565,0.342537,301387,0.287915,37328
32,33,Richmond,VA,51,51760,\t37.541290,\t-77.434769,760,223170,121183,0.543008,81700,0.366089,23766
33,34,Roanoke,VA,51,51770,\t37.270969,\t-79.941429,770,99660,36045,0.36168,27586,0.276801,22501
34,35,Sacramento,CA,06,06067,\t38.590576,\t-121.489906,067,1514460,631697,0.41711,435385,0.287485,30281
35,36,San Diego,CA,06,06073,\t32.715736,\t-117.161087,073,3317749,932279,0.280997,1035946,0.312244,31266
36,37,San Francisco,CA,06,06075,\t37.773972,\t-122.431297,075,870887,466477,0.535634,329468,0.378313,48872
37,38,Seattle,WA,53,53033,\t47.608013,\t-122.335167,033,2149970,756490,0.351861,674868,0.313896,41290
38,39,Spokane,WA,53,53063,\t47.658779,\t-117.426048,063,499072,61984,0.124199,140742,0.282007,27579
39,40,St. Louis,MO,29,29510,\t38.627003,\t-90.199402,510,311404,166652,0.535163,106698,0.342635,25339
40,41,Syracuse,NY,36,36067,\t43.088947,\t-76.154480,067,466194,95274,0.204366,122803,0.263416,30495
41,42,Tampa,FL,12,12057,\t27.964157,\t-82.452606,057,1376238,404485,0.293906,392025,0.284853,27294
42,43,TotalUS,US,0,0,0,0,,323127515,88483476,0.273835,87413147,0.270522,29300

In [9]:
markets_df.to_csv("Markets_demo_2016.csv")