In [1]:
#import dependancies
import pandas as pd
import numpy as np
import requests 
import time 
import json

from census_key import api_key

In [2]:
markets_df = pd.read_csv('Markets_for_api.csv', encoding = "ISO-8859-1", dtype=str)

In [3]:
markets_df.head(20)

,Market_id,Market_name,Market_state,State_code,FIPS_code,Lat,Long
0,1,Albany,NY,36,36001,42.6526,\t-73.7562
1,2,Atlanta,GA,13,13121,\t33.753746,\t-84.386330
2,3,Baltimore,MD,24,24510,\t39.299236,\t-76.609383
3,4,Boise,ID,16,16001,\t43.618881,\t-116.215019
4,5,Boston,MA,25,25025,\t42.361145,\t-71.057083
5,6,Buffalo,NY,36,36029,\t42.880230,\t-78.878738
6,7,Charlotte,NC,37,37119,\t35.227085,\t-80.843124
7,8,Chicago,IL,17,17031,\t41.881832,\t-87.623177
8,9,Cincinnati,OH,39,39061,\t39.103119,\t-84.512016
9,10,Columbus,OH,39,39049,\t39.983334,\t-82.983330
10,11,Dallas,TX,48,48113,\t32.779167,\t-96.808891
11,12,Denver,CO,08,08031,\t39.742043,\t-104.991531
12,13,Detroit,MI,26,26163,\t42.331429,\t-83.045753
13,14,Grand Rapids,MI,26,26081,\t42.963795,\t-85.670006
14,15,Harrisburg,PA,42,42043,\t40.263680,\t-76.890739
15,16,Hartford,CT,09,09003,\t41.763710,\t-72.685097
16,17,Houston,TX,48,48201,\t29.749907,\t-95.358421
17,18,Indianapolis,IN,18,18053,\t39.791000,\t-86.148003
18,19,Jacksonville,FL,12,12031,\t30.332184,\t-81.655647
19,20,Las Vegas,NV,32,32003,\t36.114647,\t-115.172813

In [4]:
markets_df["County_code"]=""

for index, row in markets_df.iterrows():
    FIPS = markets_df.loc[index,"FIPS_code"]
    county_code = FIPS[2:5]
    markets_df.loc[index,"County_code"] = county_code
    
#markets_df.head()

In [5]:
##Create holders for Total Population, White Alone Population, Age 20-24, Age 25 - 29, Age 30 - 34, Age 35 - 39 and Median Income
markets_df["Total_population"]=""
markets_df["Non_White_pop"]=""
markets_df["Diversity%"]=""
markets_df["Millenial_pop"]=""
markets_df["Millenial%"]=""
markets_df["Median_income"]=""

#markets_df.tail()
#There are 42 markets, just FYI

In [6]:
print("Log Start")
print("--------------------------")

for index, row in markets_df.iterrows():
    
    #set needed variables
    county = markets_df.loc[index, "County_code"]
    state = markets_df.loc[index, "State_code"]
    data = "B01001_001E,B01001A_001E,B01001_032E,B01001_033E,B01001_034E,B01001_035E,B01001_036E,B01001_037E,B01001_008E,B01001_009E,B01001_010E,B01001_011E,B01001_012E,B01001_013E,B06011_001E"
        
    query_url = "http://api.census.gov/data/2015/acs/acs1?get=" + str(data) + "&for=county:" + str(county) + "&in=state:" + str(state) + "&key=" + str(api_key)
    
    try:
        response = requests.get(query_url).json()
    
        census_data = response[1]

        for i in range(0, len(census_data)): 
            census_data[i] = int(census_data[i]) 

        print(markets_df.loc[index,"Market_id"])
        
        try:
            #sum all age data
            all_females = sum(census_data[2:8])
            all_males = sum(census_data[8:14])
            millenials = all_females + all_males
            
            total_pop = census_data[0]
            white_pop = census_data[1]
            
            non_white = total_pop - white_pop
            #print(total_pop, non_white)
            
            diversity = non_white/total_pop
            #print(diversity)

        except:
            print('error with conversion')
        
        try:
            markets_df.loc[index, "Total_population"] = total_pop
            markets_df.loc[index, "Non_White_pop"]= non_white
            markets_df.loc[index,"Diversity%"]= diversity
            markets_df.loc[index,"Millenial_pop"]= millenials
            markets_df.loc[index,"Millenial%"]= millenials/total_pop
            markets_df.loc[index,"Median_income"]=census_data[14]
        
        except:
            print('error with api call')
            
    except:
        print(query_url)


print("---------------")
print("Log End")

Log Start
--------------------------
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
http://api.census.gov/data/2015/acs/acs1?get=B01001_001E,B01001A_001E,B01001_032E,B01001_033E,B01001_034E,B01001_035E,B01001_036E,B01001_037E,B01001_008E,B01001_009E,B01001_010E,B01001_011E,B01001_012E,B01001_013E,B06011_001E&for=county:&in=state:0&key=5b32564c5f4ebf42969c99f2ac96affff18bb411
---------------
Log End

In [42]:
#Market_id 43 (last one) fails because it's the total u.s., so there's no FIPS county or state to call. 
#Build a custom call to grab total us data. Region seems to be as aggregate as we can get, so we'll need to sum

query_url = "http://api.census.gov/data/2015/acs/acs1?get=" + str(data) + "&for=region:*&key=" + str(api_key)


response = requests.get(query_url).json()
        
northeast = response[1]
midwest = response[2]
south = response[3]
west = response[4]

try:
    for i in range(0,(len(northeast)-1)):
        northeast[i] = int(northeast[i])
                       
    for i in range(0,(len(midwest)-1)):
        midwest[i] = int(midwest[i])
                       
    for i in range(0,(len(south)-1)):
        south[i] = int(south[i])
                       
    for i in range(0,(len(west)-1)):
        west[i] = int(west[i])
        
except:
    print("couldn't convert")


total_pop = northeast[0] + midwest[0] + south[0]+ west[0]
print(total_pop)

all_females = sum(northeast[2:8])+ sum(midwest[2:8]) + sum(south[2:8]) + sum(west[2:8])
all_males = sum(northeast[8:14])+sum(midwest[8:14])+sum(south[8:14])+sum(west[8:14])
millenials = all_females + all_males
print(millenials)

white_pop = northeast[1] + midwest[1] + south[1]+ west[1]
non_white = total_pop - white_pop
diversity = non_white/total_pop

#taking the average of the median
median_inc = (northeast[14] + midwest[14] + south[14] + west[14])/4

markets_df.loc[42, "Total_population"] = total_pop
markets_df.loc[42, "Non_White_pop"]= non_white
markets_df.loc[42,"Diversity%"]= diversity
markets_df.loc[42,"Millenial_pop"]= millenials
markets_df.loc[42,"Millenial%"]= millenials/total_pop
markets_df.loc[42,"Median_income"]= median_inc

321418821
86936057

In [44]:
markets_df

,Market_id,Market_name,Market_state,State_code,FIPS_code,Lat,Long,County_code,Total_population,Non_White_pop,Diversity%,Millenial_pop,Millenial%,Median_income
0,1,Albany,NY,36,36001,42.6526,\t-73.7562,001,309381,72307,0.233715,91932,0.297148,30395
1,2,Atlanta,GA,13,13121,\t33.753746,\t-84.386330,121,1010562,552714,0.546937,315955,0.312653,32192
2,3,Baltimore,MD,24,24510,\t39.299236,\t-76.609383,510,621849,428817,0.689584,206786,0.332534,26090
3,4,Boise,ID,16,16001,\t43.618881,\t-116.215019,001,434211,37102,0.0854469,123235,0.283814,29821
4,5,Boston,MA,25,25025,\t42.361145,\t-71.057083,025,778121,346209,0.44493,312964,0.402205,29770
5,6,Buffalo,NY,36,36029,\t42.880230,\t-78.878738,029,922578,204284,0.221427,244764,0.265304,29181
6,7,Charlotte,NC,37,37119,\t35.227085,\t-80.843124,119,1034070,446958,0.432232,320111,0.309564,31132
7,8,Chicago,IL,17,17031,\t41.881832,\t-87.623177,031,5238216,2286827,0.436566,1580354,0.301697,29951
8,9,Cincinnati,OH,39,39061,\t39.103119,\t-84.512016,061,807598,256893,0.318095,220814,0.273421,28142
9,10,Columbus,OH,39,39049,\t39.983334,\t-82.983330,049,1251722,398306,0.318206,402228,0.32134,30017
10,11,Dallas,TX,48,48113,\t32.779167,\t-96.808891,113,2553385,963165,0.377211,781368,0.306013,27208
11,12,Denver,CO,08,08031,\t39.742043,\t-104.991531,031,682545,156117,0.228728,254716,0.373186,34672
12,13,Detroit,MI,26,26163,\t42.331429,\t-83.045753,163,1759335,817368,0.464589,463984,0.263727,22829
13,14,Grand Rapids,MI,26,26081,\t42.963795,\t-85.670006,081,636369,128703,0.202246,182787,0.287234,26838
14,15,Harrisburg,PA,42,42043,\t40.263680,\t-76.890739,043,272983,75996,0.278391,68002,0.249107,30377
15,16,Hartford,CT,09,09003,\t41.763710,\t-72.685097,003,895841,251852,0.281135,228706,0.255298,35197
16,17,Houston,TX,48,48201,\t29.749907,\t-95.358421,201,4538028,1638834,0.361134,1390847,0.306487,29378
17,18,Indianapolis,IN,18,18053,\t39.791000,\t-86.148003,053,67979,7882,0.115948,17217,0.253269,21578
18,19,Jacksonville,FL,12,12031,\t30.332184,\t-81.655647,031,913010,355225,0.38907,275202,0.301423,27384
19,20,Las Vegas,NV,32,32003,\t36.114647,\t-115.172813,003,2114801,800065,0.378317,595825,0.28174,27607
20,21,Los Angeles,CA,06,06037,\t34.052235,\t-118.243683,037,10170292,4884940,0.480315,3063204,0.301191,26010
21,22,Louisville,KY,21,21111,\t38.328732,\t-85.764771,111,763623,207848,0.272187,208473,0.273005,27710
22,23,Miami,FL,12,12086,\t25.761681,\t-80.191788,086,2693117,660236,0.245157,739147,0.274458,21472
23,24,Nashville,TN,47,47037,\t36.174465,\t-86.767960,037,678889,244928,0.360778,232720,0.342795,29507
24,25,New Orleans,LA,22,22071,\t29.951065,\t-90.071533,071,389617,255613,0.656062,128051,0.328659,24680
25,26,New York City,NY,36,36085,\t40.730610,\t-73.935242,085,474558,119699,0.252233,122874,0.258923,35911
26,27,Orlando,FL,12,12095,\t28.538336,\t-81.379234,095,1288126,458252,0.355751,413089,0.32069,25860
27,28,Philadelphia,PA,42,42101,\t39.952583,\t-75.165222,101,1567442,910291,0.580749,519813,0.331631,23249
28,29,Phoenix,AZ,04,04013,\t33.448376,\t-112.074036,013,4167947,910774,0.218519,1154964,0.277106,29556
29,30,Pittsburgh,PA,42,42003,\t40.440624,\t-79.995888,003,1230459,240332,0.195319,336678,0.27362,29730
30,31,Portland,OR,41,41051,\t45.523064,\t-122.676483,051,790294,166985,0.211295,271204,0.343168,28482
31,32,Raleigh,NC,37,37183,\t35.787743,\t-78.644257,183,1024198,341763,0.333688,299941,0.292855,35145
32,33,Richmond,VA,51,51760,\t37.541290,\t-77.434769,760,220289,121425,0.551208,81848,0.371548,23413
33,34,Roanoke,VA,51,51770,\t37.270969,\t-79.941429,770,99897,35010,0.350461,28768,0.287977,23404
34,35,Sacramento,CA,06,06067,\t38.590576,\t-121.489906,067,1501335,603410,0.401916,434686,0.289533,28283
35,36,San Diego,CA,06,06073,\t32.715736,\t-117.161087,073,3299521,964141,0.292206,1031913,0.312746,30311
36,37,San Francisco,CA,06,06075,\t37.773972,\t-122.431297,075,864816,455455,0.52665,324088,0.374748,44157
37,38,Seattle,WA,53,53033,\t47.608013,\t-122.335167,033,2117125,721286,0.340691,658557,0.311062,40353
38,39,Spokane,WA,53,53063,\t47.658779,\t-117.426048,063,490945,55542,0.113133,140279,0.285733,25432
39,40,St. Louis,MO,29,29510,\t38.627003,\t-90.199402,510,315685,167788,0.531505,111508,0.353226,25090
40,41,Syracuse,NY,36,36067,\t43.088947,\t-76.154480,067,468463,93373,0.199318,120707,0.257666,30492
41,42,Tampa,FL,12,12057,\t27.964157,\t-82.452606,057,1349050,403437,0.299053,385038,0.285414,27099
42,43,TotalUS,US,0,0,0,0,,321418821,86478721,0.269053,86936057,0.270476,28331.2

In [45]:
markets_df.to_csv("Markets_demo_2015.csv")